### ISSUE TITLE
How to move the process of distance map generation to the Dataloader

### ISSUE THREAD

**Issue by endaoguansanlu** [wangchi95/active-boundary-loss#7]
Thank you very much for your excellent work!!! In the process of using, I have a question, how should I move the process of distance map generation to the Dataloader？Could you please give me a example if you don't mind. Looking forward to your reply! !

**Comment by wangchi95** [comment]
> Thank you very much for your excellent work!!! In the process of using, I have a question, how should I move the process of distance map generation to the Dataloader？Could you please give me a example if you don't mind. Looking forward to your reply! !


Thanks for your interest in our work. You can refer to the demo of Dataloader here.
https://github.com/wangchi95/active-boundary-loss/issues/2#issuecomment-1061658779 https://github.com/wangchi95/active-boundary-loss/issues/2#issuecomment-1062606298

**Comment by endaoguansanlu** [comment]
Thank you very much! I'll look into it!
